version: 2
updates:
  - package-ecosystem: nuget
    directory: /
    schedule:
      interval: weekly
    groups:
      dotnet:
        patterns: ["*"]
  - package-ecosystem: npm
    directory: /report-api
    schedule:
      interval: weekly
    groups:
      report-api:
        patterns: ["*"]
  - package-ecosystem: github-actions
    directory: /
    schedule:
      interval: weekly
